services:
    proxy:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - "sharednet"
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        environment:
            - VIRTUAL_HOST=192.168.1.164
            - VIRTUAL_PORT=5000
        networks:
            - "sharednet"
    redis:
        image: redis:alpine
        command: --appendonly yes
        volumes:
            - /data:/data
        networks:
            - "sharednet"
networks:
    sharednet: {}
